### ISSUE TITLE
Theme Layout does not cover full webpage

### ISSUE THREAD

**Issue by ravishwetha** [blocknotes/activeadmin_materialize_theme#4]
![Screen Shot 2021-01-10 at 4 22 46 PM](https://user-images.githubusercontent.com/18163420/104117946-1c32f700-5360-11eb-89bb-32eb9fd43f46.png)

**Comment by ravishwetha** [comment]
Followed instructions under "Installation" section on README

**Comment by blocknotes** [comment]
Sorry for the late reply @ravishwetha.
Horizontally?
That is expected. But I could evaluate an option to make it full-width 🤔

**Comment by blocknotes** [comment]
As said, this is the expected behaviour. Closing
